server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OdoruMIAGE/config.git
          clone-on-start: true
          username: lumelling
          password: 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
          default-label: master